---
name: CI

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dev dependencies
        run: poetry install
      - name: Run Black
        run: poetry run black --check vaultwarden-kube-backup
      - name: Run isort
        run: poetry run isort -c vaultwarden-kube-backup --line-length 120 --profile black
      - name: Run mypy
        run: poetry run mypy vaultwarden-kube-backup
